<?xml version="1.0" encoding="utf-8"?><Database Name="LandBank" Class="PrDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Function Name="dbo.GetStatus" Method="GetStatus">
    <Parameter Name="StatusType" Parameter="statusType" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="GetStatusResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetCities" Method="GetCities">
    <ElementType Name="GetCitiesResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CityName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetDistrictByCityId" Method="GetDistrictByCityId">
    <Parameter Name="CityId" Parameter="cityId" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetDistrictByCityIdResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DistrictName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetAssetNames" Method="GetAssetNames">
    <ElementType Name="GetAssetNamesResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AssetName" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetLandDetails" Method="GetLandDetails">
    <Parameter Name="LandId" Parameter="landId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Deptt" Parameter="deptt" Type="System.String" DbType="VarChar(1)" />
    <ElementType Name="GetLandDetailsResult">
      <Column Name="LandId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SubAssetId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SubAssetName" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="SubAssetCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AssetName" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="AssetCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LandInformation" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Location" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Area" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="BusinessPlanDetailed" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="LandStatus" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LandType" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LandUse" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DistrictName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="CityName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetAssetsWithLandCount" Method="GetAssetsWithLandCount">
    <Parameter Name="SearchText" Parameter="searchText" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="CityId" Parameter="cityId" Type="System.Int32" DbType="Int" />
    <Parameter Name="DistrictId" Parameter="districtId" Type="System.Int32" DbType="Int" />
    <Parameter Name="AssetId" Parameter="assetId" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetAssetsWithLandCountResult">
      <Column Name="AssetId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AssetName" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="SubAssetName" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="NumberOfLands" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalLandArea" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetLandByAssetId" Method="GetLandByAssetId">
    <Parameter Name="AssetId" Parameter="assetId" Type="System.Int32" DbType="Int" />
    <Parameter Name="SearchText" Parameter="searchText" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="CityId" Parameter="cityId" Type="System.Int32" DbType="Int" />
    <Parameter Name="DistrictId" Parameter="districtId" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <Parameter Name="LandUseId" Parameter="landUseId" Type="System.Int32" DbType="Int" />
    <Parameter Name="BusinessPlanId" Parameter="businessPlanId" Type="System.Int32" DbType="Int" />
    <Parameter Name="WLTStatus" Parameter="wLTStatus" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="GetLandByAssetIdResult">
      <Column Name="LandId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Area" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Location" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="AssetName" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="SubAssetName" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="LandStatus" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LandType" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LandUse" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DistrictName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="CityName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>